/* Independent analytical views, backed by complete-month aggregates. */
const renderObservatory = (() => {
  let pending;
  const states = {};
  const nf = new Intl.NumberFormat('es-PE');
  const fmt = n => n == null ? 'Reservado' : nf.format(n);
  const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const sum = a => a.some(n => n == null) ? null : a.reduce((a,b) => a+b,0);
  const delta = (a,b) => a == null || b == null ? null : a-b;
  const pct = (a,b) => a == null || !b ? 'No comparable' : `${a>=b?'+':''}${((a-b)/b*100).toFixed(1)}%`;
  const month = s => new Date(`${s}-15T12:00:00`).toLocaleDateString('es-PE',{month:'short',year:'2-digit'});
  const shift = (s,n) => {const d=new Date(`${s}-15T12:00:00`);d.setMonth(d.getMonth()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;};
  const colors = ['#32c5ab','#edcd62','#84aee5'];
  function chart(labels, lines, bands, split) {
    const W=900,H=310,L=65,R=25,T=24,B=45, values=lines.flatMap(l=>l.values).concat((bands||[]).flat()).filter(Number.isFinite);
    const max=Math.max(1,...values)*1.14, x=i=>L+i*(W-L-R)/Math.max(1,labels.length-1), y=v=>H-B-v/max*(H-T-B);
    let svg=Array.from({length:5},(_,i)=>{const v=max*i/4;return `<line x1="${L}" x2="${W-R}" y1="${y(v)}" y2="${y(v)}" class="oa-grid"/><text x="${L-12}" y="${y(v)+4}" text-anchor="end">${nf.format(Math.round(v))}</text>`;}).join('');
    if(bands) {const points=bands.map((v,i)=>v?[x(i),y(v[1])]:null).filter(Boolean).concat(bands.map((v,i)=>v?[x(i),y(v[0])]:null).filter(Boolean).reverse());svg+=`<polygon points="${points.map(p=>p.join(',')).join(' ')}" fill="#648cc0" opacity=".23"/>`;}
    if(split!=null)svg+=`<line x1="${x(split)}" x2="${x(split)}" y1="${T}" y2="${H-B}" stroke="#93a8b6" stroke-dasharray="4 5"/>`;
    lines.forEach((line,k)=>{let start=true;const path=line.values.map((v,i)=>{if(v==null){start=true;return '';}const p=`${start?'M':'L'}${x(i)},${y(v)}`;start=false;return p;}).join(' ');svg+=`<path d="${path}" fill="none" stroke="${colors[k]}" stroke-width="3" ${line.dash?'stroke-dasharray="6 5"':''}/>`;line.values.forEach((v,i)=>{if(v!=null)svg+=`<circle cx="${x(i)}" cy="${y(v)}" r="3.5" fill="${colors[k]}" tabindex="0"><title>${esc(labels[i])}: ${fmt(v)} · ${esc(line.name)}</title></circle>`;});});
    labels.forEach((v,i)=>{if(i%Math.ceil(labels.length/10)===0||i===labels.length-1)svg+=`<text x="${x(i)}" y="${H-14}" text-anchor="middle">${esc(v)}</text>`;});
    return `<div class="oa-legend">${lines.map((l,i)=>`<span><i style="background:${colors[i]}"></i>${esc(l.name)}</span>`).join('')}${bands?'<span><i style="background:#648cc0"></i>Rango empírico</span>':''}</div><div class="oa-scroll"><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(lines.map(l=>l.name).join(' / '))}">${svg}</svg></div>`;
  }
  const kpi=(label,value,note,tone='')=>`<div><span>${label}</span><strong class="${tone}">${value}</strong><small>${note}</small></div>`;
  const heading=(eyebrow,title)=>`<div class="oa-section-title"><small>${eyebrow}</small><h3>${title}</h3></div>`;
  function setup(data) {
    data.index=new Map(data.monthly.map(r=>[`${r[1]}:${r[2]}:${r[0]}`,r]));
    data.hourIndex=new Map();data.hourly.forEach(r=>{const key=`${r[1]}:${r[2]}`;if(!data.hourIndex.has(key))data.hourIndex.set(key,[]);data.hourIndex.get(key).push(r);});
    return data;
  }
  function cell(d,s,m,department=s.department,field=3) {const i=d.months.indexOf(m);return i<0?null:(d.index.get(`${department}:${s.crime}:${i}`)?.[field]??(d.index.has(`${department}:${s.crime}:${i}`)?null:0));}
  function controls(d,s,type) {
    const options=(a,selected)=>a.map(([v,t])=>`<option value="${esc(v)}" ${String(selected)===String(v)?'selected':''}>${esc(t)}</option>`).join('');
    const select=(name,title,a)=>`<label>${title}<select data-field="${name}">${options(a,s[name])}</select></label>`;
    return `<div class="oa-controls">${type==='temporal'?select('from','DESDE (MES)',d.months.map(m=>[m,month(m)]))+select('to','HASTA (MES)',d.months.map(m=>[m,month(m)])):select('horizon','HORIZONTE',[[1,'1 mes'],[3,'3 meses'],[6,'6 meses']])+select('coverage','RANGO EMPÍRICO',[[80,'80% nominal'],[95,'95% nominal']])}${select('department','DEPARTAMENTO',d.departments.map((v,i)=>[i,v]))}<label>DELITO<select data-field="crime"><option value="0" ${s.crime===0?'selected':''}>Todos los delitos</option><optgroup label="Delitos prioritarios">${options(d.crimes.slice(1,6).map((v,i)=>[i+1,v]),s.crime)}</optgroup><optgroup label="Otros delitos">${options([[6,'OTROS DELITOS']],s.crime)}</optgroup></select></label></div><p class="oa-validation" role="status"></p>`;
  }
  function temporal(d,s) {
    const selected=d.months.filter(m=>m>=s.from&&m<=s.to), current=selected.map(m=>cell(d,s,m)), previous=selected.map(m=>cell(d,s,shift(m,-12)));
    const a=sum(current),b=sum(previous),diff=delta(a,b),valid=sum(selected.map(m=>cell(d,s,m,s.department,4)));
    const peak=current.some(Number.isFinite)?current.indexOf(Math.max(...current.filter(Number.isFinite))):-1;
    const rows=(d.hourIndex.get(`${s.department}:${s.crime}`)||[]).filter(r=>selected.includes(d.months[r[0]]));
    const heat=Array.from({length:7},()=>Array(8).fill(0));rows.forEach(r=>{heat[r[3]][r[4]]=heat[r[3]][r[4]]==null||r[5]==null?null:heat[r[3]][r[4]]+r[5];});
    const hmax=Math.max(1,...heat.flat().filter(Number.isFinite));
    const heatTable=`<div class="oa-scroll"><table class="oa-heat"><thead><tr><th>Día / hora</th>${Array.from({length:8},(_,i)=>`<th>${i*3}–${i*3+2}h</th>`).join('')}</tr></thead><tbody>${heat.map((row,i)=>`<tr><th>${['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'][i]}</th>${row.map(v=>`<td style="background:${v==null?'#26343d':`rgba(50,197,171,${.07+.65*v/hmax})`}" title="${fmt(v)}">${v==null?'R':fmt(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
    const endYear=Number(s.to.slice(0,4)), years=[endYear-2,endYear-1,endYear], season=years.map(y=>Array.from({length:12},(_,i)=>cell(d,s,`${y}-${String(i+1).padStart(2,'0')}`))),max=Math.max(1,...season.flat().filter(Number.isFinite));
    const seasonal=`<div class="oa-scroll"><table class="oa-heat"><thead><tr><th>Año</th>${Array.from({length:12},(_,i)=>`<th>${month(`2020-${String(i+1).padStart(2,'0')}`).split(' ')[0]}</th>`).join('')}</tr></thead><tbody>${season.map((row,i)=>`<tr><th>${years[i]}</th>${row.map(v=>`<td style="background:rgba(237,205,98,${v==null?.03:.07+.6*v/max})" title="${fmt(v)}">${v==null?'—':fmt(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
    const territories=d.departments.map((name,i)=>({name,i,a:sum(selected.map(m=>cell(d,s,m,i))),b:sum(selected.map(m=>cell(d,s,shift(m,-12),i)))})).filter(r=>r.i&&r.a!=null&&r.b!=null).map(r=>({...r,diff:r.a-r.b})).sort((a,b)=>Math.abs(b.diff)-Math.abs(a.diff)).slice(0,8);
    const scale=Math.max(1,...territories.map(r=>Math.abs(r.diff)));
    const bars=territories.map(r=>`<div class="oa-bar"><span>${esc(r.name)}</span><div><i style="${r.diff<0?'right:50%;background:#32c5ab':'left:50%;background:#ef777f'};width:${Math.abs(r.diff)/scale*48}%"></i></div><b class="${r.diff<0?'oa-good':'oa-bad'}">${r.diff>0?'+':''}${fmt(r.diff)}</b></div>`).join('');
    return `<div class="oa-kpis">${kpi('Denuncias registradas',fmt(a),'Período seleccionado')}${kpi('Variación interanual',pct(a,b),'Mismos meses del año anterior',diff==null?'':diff<0?'oa-good':'oa-bad')}${kpi('Diferencia absoluta',diff==null?'No comparable':`${diff>0?'+':''}${fmt(diff)}`,'Denuncias, no personas')}${kpi('Cobertura de fecha del hecho',a&&valid!=null?`${(valid/a*100).toFixed(1)}%`:'No disponible','Para el análisis de día y hora')}</div>
      <div class="oa-main"><section>${heading('EVOLUCIÓN COMPARADA','¿Cómo cambió la incidencia?')}${chart(selected.map(month),[{name:'Período seleccionado',values:current},{name:'Mismos meses del año anterior',values:previous,dash:true}])}<p class="oa-note">Solo meses completos. Un punto reservado o sin período comparable se muestra como una interrupción, no como cero.</p></section><aside>${heading('LECTURA DEL PERÍODO','Hallazgos para el observatorio')}<p><b>${pct(a,b)}</b><br>Frente a los mismos meses del año anterior, dentro del territorio y delito elegidos.</p><p><b>${peak<0?'Sin máximo disponible':month(selected[peak])}</b><br>${peak<0?'':`${fmt(current[peak])} denuncias: mayor valor del período seleccionado.`}</p><p>Una variación del registro no demuestra por sí sola un cambio en la ocurrencia real del delito.</p></aside></div>
      <div class="oa-two"><section>${heading('PATRÓN SEMANAL','Día y franja horaria del hecho')}${heatTable}<p class="oa-note">Hechos de las denuncias registradas en el período. R: celda con datos reservados; no equivale a cero. Las franjas no prueban causas.</p></section><section>${heading('CAMBIO TERRITORIAL','¿Dónde cambió más el registro?')}<div class="oa-bars">${bars}</div><p class="oa-note">Ocho mayores diferencias absolutas, a nivel nacional, para el mismo delito y período. Verde: disminución; rojo: aumento.</p></section></div>
      <section class="oa-full">${heading('ESTACIONALIDAD DESCRIPTIVA','Meses y años, en perspectiva')}${seasonal}<p class="oa-note">Tres años hasta el año elegido. Mayor intensidad: más denuncias. —: fuera de cobertura o reservado. Este gráfico amplía el período para observar patrones; no confirma estacionalidad estadística.</p></section>`;
  }
  function predictive(d,s) {
    const f=d.forecasts[`${s.department}:${s.crime}`],last=d.months.at(-1), future=Array.from({length:s.horizon},(_,i)=>shift(last,i+1));
    if(!f||f.status!=='ok')return `<section class="oa-full oa-empty"><h3>No hay una proyección publicable para esta selección</h3><p>${esc(f?.reason||'No hay serie disponible.')}</p><p>Consulta el análisis temporal o selecciona un territorio con mayor volumen. No se estiman valores sobre celdas reservadas.</p></section>`;
    const history=d.months.slice(-18), actual=history.map(m=>cell(d,s,m)), labels=history.concat(future).map(month), forecast=Array(history.length-1).fill(null).concat(actual.at(-1),f.forecast.slice(0,s.horizon)),bands=Array(history.length).fill(null).concat(f.intervals[s.coverage].slice(0,s.horizon));
    const rank=d.departments.map((name,i)=>({name,i,f:d.forecasts[`${i}:${s.crime}`]})).filter(r=>r.i&&r.f?.status==='ok').sort((a,b)=>b.f.forecast[0]-a.f.forecast[0]).slice(0,10);
    return `<div class="oa-kpis">${kpi('Próximo mes',fmt(f.forecast[0]),month(future[0]))}${kpi(`Rango ${s.coverage}% nominal`,`${fmt(f.intervals[s.coverage][0][0])} – ${fmt(f.intervals[s.coverage][0][1])}`,'Empírico; no garantiza cobertura')}${kpi('Error medio en prueba',fmt(f.mae),'Denuncias · últimos 12 meses, a un paso')}${kpi('Historia disponible',fmt(f.history_months),'Meses completos')}</div>
      <div class="oa-main"><section>${heading('ESCENARIO ESTADÍSTICO','Histórico y proyección del registro')}${chart(labels,[{name:'Observado',values:actual.concat(Array(s.horizon).fill(null))},{name:'Proyección',values:forecast,dash:true}],bands,history.length-1)}<p class="oa-note">${esc(f.model)} · Corte: ${month(last)}. El rango refleja errores históricos, no una certeza de lo que ocurrirá.</p></section><aside>${heading('ALCANCE DEL MODELO','Qué puede y qué no puede decir')}<p><b>${esc(f.model)}</b><br>Elegido por menor error en ${f.selection_cuts} cortes históricos previos a la prueba final.</p><p><b>Registro de denuncias</b><br>Se estima volumen agregado; no personas, responsables ni lugares exactos.</p><p>Un cambio de registro, cobertura o política puede invalidar el patrón histórico. La lectura requiere criterio del analista.</p></aside></div>
      <div class="oa-two"><section>${heading('VERIFICACIÓN RETROSPECTIVA','¿Qué tan cerca estuvo de los datos reales?')}${chart(f.backtest.map(r=>month(d.months[r[0]])),[{name:'Observado',values:f.backtest.map(r=>r[2])},{name:'Pronóstico a un paso',values:f.backtest.map(r=>r[1]),dash:true}])}<p class="oa-note">Cada punto fue estimado solo con meses anteriores. Estos 12 meses no se usaron para elegir el modelo.</p></section><section>${heading('SELECCIÓN DEL MÉTODO','Comparación de modelos')}<table><thead><tr><th>Método</th><th>Error MAE</th></tr></thead><tbody>${f.models.map(m=>`<tr><th>${esc(m.name)}${m.name===f.model?' <span class="oa-selected">Elegido</span>':''}</th><td>${fmt(m.mae)}</td></tr>`).join('')}</tbody></table><p class="oa-note">Menor MAE es mejor. Esta tabla evalúa horizontes de 1 a 6 meses en el conjunto de selección; no es el mismo error de la prueba final.</p><details><summary>Metodología y límites</summary><p>${esc(d.methodology)}</p><p>Estacional: repite el mismo mes del año anterior. Promedio: media de los seis meses previos. Holt: nivel y tendencia amortiguada. La banda utiliza cuantiles de errores por horizonte; su cobertura nominal es aproximada y la muestra de calibración es limitada.</p></details></section></div>
      <section class="oa-full">${heading('PANORAMA TERRITORIAL','Volumen esperado el próximo mes')}<div class="oa-scroll"><table><thead><tr><th>Departamento</th><th>Estimación</th><th>Rango ${s.coverage}% nominal</th><th>Modelo</th><th>MAE de prueba</th></tr></thead><tbody>${rank.map(r=>`<tr><th>${esc(r.name)}</th><td>${fmt(r.f.forecast[0])}</td><td>${r.f.intervals[s.coverage][0].map(fmt).join(' – ')}</td><td>${esc(r.f.model)}</td><td>${fmt(r.f.mae)}</td></tr>`).join('')}</tbody></table></div><p class="oa-note">Hasta diez departamentos con mayor volumen esperado para el delito elegido, independientemente del filtro territorial. No es un ranking de riesgo por habitante. Territorios sin evaluación suficiente se excluyen.</p></section>`;
  }
  function paint(d,type) {
    const root=document.getElementById(type==='temporal'?'observatorioTemporal':'observatorioPredictivo'),s=states[type];
    root.innerHTML=`<header class="oa-header"><div><small>OBSERVATORIO DEL CRIMEN / ${type==='temporal'?'EVIDENCIA HISTÓRICA':'ESCENARIOS Y VALIDACIÓN'}</small><h2>${type==='temporal'?'Análisis temporal':'Análisis predictivo'}</h2><p>${type==='temporal'?'Evolución, patrones y cambios territoriales del registro de denuncias.':'Proyecciones agregadas con evaluación histórica e incertidumbre visible.'}</p></div><button type="button" class="oa-export" title="Imprimir o guardar como PDF" aria-label="Imprimir o guardar como PDF"><i class="fas fa-file-pdf" aria-hidden="true"></i> Exportar PDF</button></header>${controls(d,s,type)}<div class="oa-context">${esc(d.crimes[s.crime])} · ${esc(d.departments[s.department])} · ${type==='temporal'?`${month(s.from)} – ${month(s.to)}`:`Corte: ${month(d.months.at(-1))} · ${s.horizon} meses`}<span>Meses completos · Fuente: SIDPOL</span></div>${type==='temporal'?temporal(d,s):predictive(d,s)}<footer class="oa-footer">FUENTE: SIDPOL · Agregación por mes de registro · Actualización: ${esc(d.generated_at.slice(0,10))}. ${esc(d.privacy)}</footer>`;
    const selectedMonths=type==='temporal'?d.months.filter(m=>m>=s.from&&m<=s.to):d.months;
    root.querySelector('.oa-controls').insertAdjacentHTML('afterend',Portal.selectionTotal(`${type==='temporal'?'Total del periodo':'Total histórico observado'} · ${d.crimes[s.crime]}`,sum(selectedMonths.map(m=>cell(d,s,m))),`${selectedMonths[0]} al ${selectedMonths.at(-1)} · ${d.departments[s.department]} · SIDPOL · Acumulado mensual${type==='temporal'?'':'; no es una proyección'}`));
    root.querySelectorAll('[data-field]').forEach(el=>el.addEventListener('change',()=>{const key=el.dataset.field,value=['department','crime','horizon','coverage'].includes(key)?Number(el.value):el.value;if((key==='from'&&value>s.to)||(key==='to'&&value<s.from)){el.value=s[key];root.querySelector('.oa-validation').textContent='El mes inicial debe ser anterior o igual al mes final.';return;}s[key]=value;paint(d,type);}));
    root.querySelector('.oa-export').addEventListener('click',()=>{
      Portal.report({title:type==='temporal'?'Análisis temporal':'Proyecciones',source:'SIDPOL',cut:d.months.at(-1),content:root,filters:[['Delito',d.crimes[s.crime]],['Departamento',d.departments[s.department]],['Periodo observado',`${selectedMonths[0]} al ${selectedMonths.at(-1)}`],['Cobertura','Meses completos'],...(type==='temporal'?[]:[['Horizonte',`${s.horizon} meses`],['Intervalo',`${s.coverage}% nominal`]])]});
    });
    Portal.formatDates(root);
  }
  return async function(type) {
    const root=document.getElementById(type==='temporal'?'observatorioTemporal':'observatorioPredictivo');if(!root)return;
    if(states[type]&&root.children.length)return;
    root.innerHTML='<p class="oa-loading" role="status">Cargando series y evaluación estadística...</p>';
    try {if(!pending)pending=fetch('data/api/observatorio/analisis.json').then(r=>{if(!r.ok)throw Error('Fuente no disponible');return r.json();}).then(d=>{if(d.schema!==1||!d.months?.length||!d.forecasts)throw Error('Fuente incompleta');return setup(d);});const d=await pending;states[type]??={department:0,crime:1,from:d.months.filter(m=>m.startsWith(d.months.at(-1).slice(0,4)))[0],to:d.months.at(-1),horizon:3,coverage:80};paint(d,type);} catch(error){pending=null;root.innerHTML='<div class="oa-empty"><h3>Análisis no disponible</h3><p>No se pudo cargar la fuente analítica. No se mostrarán cifras estimadas como si fueran datos reales.</p><button type="button">Reintentar</button></div>';root.querySelector('button').onclick=()=>{delete states[type];renderObservatory(type);};console.error(error);}
  };
})();
